# swagger.yml
openapi: 3.0.0
info: 
  title: "CW2 API"
  description: "An API to grab data from the CW2 database"
  version: "1.0.0"


servers:
  - url: "/api"

components:
  parameters:
    id:
      name: "id"
      in: "path"
      required: true
      schema:
        type: "string"
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string



paths:
  /User:
    get:
      operationId: "User.getall"
      tags:
        - "User"
      summary: "Get all the users"
      responses:
        '200':
          description: "A list of all the users"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      operationId: "User.create"
      tags:
        - "User"
      summary: "Create a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: "User created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      operationId: "User.delete"
      tags:
        - "User"
      summary: "Delete a user"
      responses:
        '200':
          description: "User deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /User/{id}:
    patch:
      operationId: "User.update"
      tags:
        - "User"
      summary: "Update a user"
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      
      responses:
        '200':
          description: "User updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        
  